<table>
    <tr>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">customer_id</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">work_order_isp</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">work_order_cfocn</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">subscriber_no</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">isp_ex_work_order_isp</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">status</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">name</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">phone</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">address</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">zone</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">city</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">port</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">pos_speed_id</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">applicant_team_install</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">team_install</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">create_time</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">completed_time</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">date_ex_complete_old_order</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">dismantle_date</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">dismantle_order_cfocn</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">lay_fiber</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">remark_first</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">reactive_date</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">change_splitter_date</th>
        <th style="vertical-align:middle; text-align:center; background:#ACB9CA;">relocation_date</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">start_payment_date</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">last_payment_date</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">initial_installation_order_complete_time</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">first_relocation_order_complete_date</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">payment_date</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">payment_status</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">month</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">day</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">deadline</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">day_remaining</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">customer_type</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">new_installation_fee</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">fiber_jumper_fee</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">digging_fee</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">first_payment_period</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">initial_payment_period</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">rental_price</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">ppcc</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">number_of_pole</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">rental_pole</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">other_fee</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">discount</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">total</th>
        <th style="vertical-align:middle; text-align:center; background:#C6E0B4;">remark_second</th>
    </tr>
    {{-- <tr>
        <td style="vertical-align:middle; text-align:center;">00000019</td>
        <td style="vertical-align:middle; text-align:center;">133995</td>
        <td style="vertical-align:middle; text-align:center;">133995</td>
        <td style="vertical-align:middle; text-align:center;">NIS2022121601</td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;">Active </td>
        <td style="vertical-align:middle; text-align:center;">中信大厦</td>
        <td style="vertical-align:middle; text-align:center;">0969696809,0965115982</td>
        <td style="vertical-align:middle; text-align:center;">Street Nº 124, Phum 3 , Preah Sihanouk</td>
        <td style="vertical-align:middle; text-align:center;">SHVA</td>
        <td style="vertical-align:middle; text-align:center;">SHV</td>
        <td style="vertical-align:middle; text-align:center;"> Shva-21 TEAM SHV 1:32 HOME</td>
        <td style="vertical-align:middle; text-align:center;">1:32</td>
        <td style="vertical-align:middle; text-align:center;">CFOCN</td>
        <td style="vertical-align:middle; text-align:center;">TEAM SHV</td>
        <td style="vertical-align:middle; text-align:center;">12/16/2022</td>
        <td style="vertical-align:middle; text-align:center;">12/16/2022</td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;">100</td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;">12/16/2023</td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;">85</td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;">12</td>
        <td style="vertical-align:middle; text-align:center;">12</td>
        <td style="vertical-align:middle; text-align:center;">7</td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
        <td style="vertical-align:middle; text-align:center;"></td>
    </tr> --}}
</table>